/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 33
#define YY_END_OF_BUFFER 34
static yyconst short int yy_acclist[87] =
    {   0,
       34,   32,   33,    3,   32,   33,    3,   33,   23,   32,
       33,   32,   33,   26,   32,   33,   27,   32,   33,   18,
       32,   33,   16,   32,   33,   25,   32,   33,   17,   32,
       33,   19,   32,   33,   15,   32,   33,   24,   32,   33,
       20,   32,   33,   22,   32,   33,   21,   32,   33,   10,
       32,   33,   28,   32,   33,   29,   32,   33,   12,   32,
       33,   30,   32,   33,   31,   32,   33,    3,    9,    5,
        4,    2,   14,   15,    6,    8,    7,   10,   10,   11,
       14,    2,   13,   10,   11,    1
    } ;

static yyconst short int yy_accept[52] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   69,   70,   70,
       71,   72,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   83,   84,   85,   86,   86,   87,
       87
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       20,    1,   21,    1,   22,    1,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   23,    1,   24,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[25] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[54] =
    {   0,
        0,    0,   79,   80,   23,   25,   61,   26,   80,   80,
       80,   63,   80,   62,   67,   18,   80,   57,   56,   55,
       19,   80,   80,   20,   80,   80,   33,   80,   40,   80,
       80,   32,   63,   54,   35,   80,   80,   80,   34,   36,
       38,   80,   57,   46,   50,   47,   48,   55,   80,   80,
       50,   39,   36
    } ;

static yyconst short int yy_def[54] =
    {   0,
       50,    1,   50,   50,   50,   50,   50,   51,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   51,   50,
       50,   50,   52,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   52,   53,   50,   50,   50,   53,   50,    0,
       50,   50,   50
    } ;

static yyconst short int yy_nxt[105] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,    4,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   30,   34,
       31,   35,   39,   40,   27,   27,   48,   39,   40,   43,
       39,   41,   30,   42,   31,   32,   34,   39,   35,   46,
       29,   47,   39,   44,   46,   39,   47,   46,   49,   47,
       46,   47,   44,   45,   44,   46,   47,   45,   46,   47,
       44,   38,   37,   36,   33,   32,   32,   28,   50,    3,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50
    } ;

static yyconst short int yy_chk[105] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,    8,   16,
        8,   16,   21,   24,   27,   27,   53,   21,   24,   52,
       21,   24,   29,   32,   29,   32,   35,   39,   35,   40,
       51,   41,   39,   44,   40,   39,   41,   40,   44,   41,
       46,   47,   48,   45,   43,   46,   47,   34,   46,   47,
       33,   20,   19,   18,   15,   14,   12,    7,    3,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "analizador.l"
#define INITIAL 0
#line 2 "analizador.l"


/* Compilador para el lenguaje de C--
* Author: Edgar Aviles
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>



/* ── Token IDs ─── */

/* Keywords */
#define TK_INT 1
#define TK_FLOAT 2
#define TK_STRING 3
#define TK_RETURN 4
#define TK_IF 5
#define TK_ELSE 6
#define TK_WHILE 7
#define TK_READ 8
#define TK_WRITE 9
#define TK_VOID 10


/* OPERATIONS */
#define TK_PLUS 11
#define TK_MINUS 12
#define TK_MULT 13
#define TK_DIVISION 14
#define TK_LESSTHAN 15
#define TK_LESSEQ 16
#define TK_MORETHAN 17
#define TK_MOREEQ 18
#define TK_EQUAL 19
#define TK_DIF 20

/* Others */
#define TK_ASSIGN 21
#define TK_SEMICOLON 22
#define TK_COMMA 23
#define TK_DQUOTE 24
#define TK_OPAREN     25
#define TK_CPAREN     26
#define TK_OBRACKET   27
#define TK_CBRACKET   28
#define TK_OCURLY     29
#define TK_CCURLY     30

/* Value tokens  */
#define TK_ID         31
#define TK_INT_NUM    32
#define TK_FLOAT_NUM  33
#define TK_STRING_LIT 34


/*  Tables structures */
#define MAX_LEXEME   256
#define MAX_NUMS     500
#define MAX_STRINGS  500

struct ID {
    /* Esta es la variable como tal   */
    char      lexeme[MAX_LEXEME];
    int       linea;
    struct ID *next;
};
/*  Se inicia en 0 la tabla /lista enlazada */
struct ID *idSymTbl = NULL;

/* Tablas de números para int o float */
typedef struct {
    char lexeme[256];
    int  token_type;  /* TK_INT_NUM o TK_FLOAT_NUM */
    int  linea;
} EntryNum;

EntryNum tabla_nums[MAX_NUMS];
/* Se inicia la tabla en 0 */
int count_nums = 0;


/* Tabla de strings */
typedef struct {
    char lexeme[MAX_LEXEME];
    int  linea;
} EntryString;

EntryString tabla_strings[MAX_STRINGS];
/* Se inicia la tabla en 0 */
int count_strings = 0;


/* Lista de tokens */
typedef struct {
    int  token_id;
    int  table_index;   /* índice en su tabla, -1 si no aplica */
    int  linea;
    char lexeme[MAX_LEXEME];
} TokenEntry;

TokenEntry token_list[5000];
int count_tokens = 0;
int error_count  = 0;

/* tabla para buscar los key words */
typedef struct {
    char *word;
    int   token;
} Keyword;

Keyword keywords[] = {
    {"int",    TK_INT},
    {"float",  TK_FLOAT},
    {"string", TK_STRING},
    {"return", TK_RETURN},
    {"if",     TK_IF},
    {"else",   TK_ELSE},
    {"while",  TK_WHILE},
    {"read",   TK_READ},
    {"write",  TK_WRITE},
    {"void",   TK_VOID},
    {NULL, 0}             /* centinela para saber dónde termina */
};


/* Prototipos  */
/* es un aviso sobre lo que se va a declarar despues y el como */
int lookup_keyword (char *word);

/* es al id, se va a buscar cual es */
struct ID*  lookUp_ID (char *lexeme, int linea);
int  insert_num (char *lexeme, int tipo, int linea);
int  insert_string (char *lexeme, int linea);
void add_token (int token_id, int table_index, int linea, char *lexeme);
void to_lower (char *str);
void print_token_list (void);
void print_table_ids (void);
void print_table_nums (void);
void print_table_strings (void);
void print_error (char *msg, int linea, char *lexeme);


/* OPCIONES extra */
/* conteo de lineas */
/* para evitar el end of file */
/* ── Regex con nombre ──────── */
/* primero la comilla doble, luego cualquier cosa excepto comillas o salto de linea, al final otra comilla doble */
/* inicia el comentarios, cualquier cosa que no sea asterisco, siendo que uno o mas asteriscos no cierran el comentario, luego ya el asterisco mas la diagonal, cierra el comentario */
/*REGLAAAAAS */
#line 579 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 175 "analizador.l"


#line 733 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 51 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 80 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 177 "analizador.l"
{ /* se ignora completamente los comentarios */  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 180 "analizador.l"
{ 
  /* se inicio pero no se cerro */
  print_error("Unterminated comment", yylineno, yytext);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 186 "analizador.l"
{ /* se ignoran los espacios en blanco */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 188 "analizador.l"
{
  /* para obtener lo que contiene el string literalmente
  * se saca el contenido, se le quitan las dobles comillas, se pone en minuscula y de ahi se inserta el contenido y la linea 
  * luego se agrega el token, si es con lista, el id, linea y texto 
  */
  char content[MAX_LEXEME];
  strncpy(content, yytext + 1, yyleng - 2);
  content[yyleng - 2] = '\0';
  to_lower(content);
  int idx = insert_string(content, yylineno);
  add_token(TK_STRING_LIT, idx, yylineno, yytext);
  return TK_STRING_LIT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 202 "analizador.l"
{
  /* si el estring no se cerro totalmente, se pone el error */
 print_error("Unterminated string literal", yylineno, yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 208 "analizador.l"
{ add_token(TK_LESSEQ, -1, yylineno, yytext); return TK_LESSEQ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 209 "analizador.l"
{ add_token(TK_MOREEQ, -1, yylineno, yytext); return TK_MOREEQ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 210 "analizador.l"
{ add_token(TK_EQUAL,  -1, yylineno, yytext); return TK_EQUAL;  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 211 "analizador.l"
{ add_token(TK_DIF, -1, yylineno, yytext); return TK_DIF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 213 "analizador.l"
{
  /* copia el codigo para guardarlo y se asegure que sea solo la parte del id, tambien lo pasa a minuscula */
  char lower[MAX_LEXEME];
  strncpy(lower, yytext, MAX_LEXEME - 1);
  lower[MAX_LEXEME - 1] = '\0';
  to_lower(lower);
  /* buscar si es palabra reservada */
  int kw = lookup_keyword(lower);
  if (kw != 0) {
  /* es keyword */
  add_token(kw, -1, yylineno, yytext);
  return kw;
  } else {
  /* es identificador */
  struct ID *entry = lookUp_ID(lower, yylineno);
  /*busca y asigna el indice*/
  int idx = 0;
  struct ID *tp = idSymTbl;
  while (tp != entry) { tp = tp->next; idx++; }
  add_token(TK_ID, idx, yylineno, yytext);
  return TK_ID;
  }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 237 "analizador.l"
{
  /* error de doble guion bajo*/
  print_error("Invalid identifier: double underscore", yylineno, yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 241 "analizador.l"
{
  /* error de solo un guion bajo*/ 
  print_error("Invalid identifier: underscore alone", yylineno, yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 247 "analizador.l"
{
  /* le asigna un indice en la tabla de numero, de ahi mete el indice que obtuvo con la informacion en la tabla general de tokens */
  int idx = insert_num(yytext, TK_FLOAT_NUM, yylineno);
  add_token(TK_FLOAT_NUM, idx, yylineno, yytext);
  return TK_FLOAT_NUM;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 254 "analizador.l"
{
  /* error de digito con punto al final  */
  print_error("Invalid real: missing decimal part", yylineno, yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 259 "analizador.l"
{
  /* inserta el numero (el numero en si, el id de numero int, y la linea), de ahi mete el toquen con el indice que se genero, y la misma info a la de tokens generales */
  int idx = insert_num(yytext, TK_INT_NUM, yylineno);
  /* si no quisiera guardar otra vez el lexema (lo que es la palabrta o numero) se pone un null en el yytext */
  add_token(TK_INT_NUM, idx, yylineno, yytext);
  return TK_INT_NUM;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 267 "analizador.l"
{ add_token(TK_PLUS, -1, yylineno, yytext); return TK_PLUS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 268 "analizador.l"
{ add_token(TK_MINUS, -1, yylineno, yytext); return TK_MINUS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 269 "analizador.l"
{ add_token(TK_MULT, -1, yylineno, yytext); return TK_MULT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 270 "analizador.l"
{ add_token(TK_DIVISION, -1, yylineno, yytext); return TK_DIVISION; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 271 "analizador.l"
{ add_token(TK_LESSTHAN, -1, yylineno, yytext); return TK_LESSTHAN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 272 "analizador.l"
{ add_token(TK_MORETHAN, -1, yylineno, yytext); return TK_MORETHAN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 273 "analizador.l"
{ add_token(TK_ASSIGN, -1, yylineno, yytext); return TK_ASSIGN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 275 "analizador.l"
{ print_error("Invalid character: '!' without '='", yylineno, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 277 "analizador.l"
{ add_token(TK_SEMICOLON, -1, yylineno, yytext); return TK_SEMICOLON; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 278 "analizador.l"
{ add_token(TK_COMMA, -1, yylineno, yytext); return TK_COMMA; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 279 "analizador.l"
{ add_token(TK_OPAREN, -1, yylineno, yytext); return TK_OPAREN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 280 "analizador.l"
{ add_token(TK_CPAREN, -1, yylineno, yytext); return TK_CPAREN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 281 "analizador.l"
{ add_token(TK_OBRACKET, -1, yylineno, yytext); return TK_OBRACKET; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 282 "analizador.l"
{ add_token(TK_CBRACKET, -1, yylineno, yytext); return TK_CBRACKET; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 283 "analizador.l"
{ add_token(TK_OCURLY, -1, yylineno, yytext); return TK_OCURLY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 284 "analizador.l"
{ add_token(TK_CCURLY, -1, yylineno, yytext); return TK_CCURLY; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 286 "analizador.l"
{ /*regresa 0 para que el while acabe */  return 0; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 287 "analizador.l"
{ print_error("Invalid character", yylineno, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 289 "analizador.l"
ECHO;
	YY_BREAK
#line 1053 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 51 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 51 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 50);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 289 "analizador.l"


/* ── to_lower: convierte string a minúsculas ── */
void to_lower(char *str) {
    int i;
    for ( i = 0; str[i]; i++)
        str[i] = tolower((unsigned char)str[i]);
}
/* buscar key word */
int lookup_keyword(char *word) {
    int i;
    for (i = 0; keywords[i].word != NULL; i++)
        if (strcmp(keywords[i].word, word) == 0)
            return keywords[i].token;
    return 0;
}


/* buscar o agregar la variabel */
struct ID* lookUp_ID(char *lexeme, int linea) {
  struct ID *tp = idSymTbl;

  /* buscar si ya existe */
  while (tp) {
    if (strcmp(tp->lexeme, lexeme) == 0)
      return tp;
    tp = tp->next;
  }

  /* no existe — agregar al inicio de la lista */
  /*guarda espacio para este */
  tp = (struct ID*) malloc(sizeof(struct ID));
  /* coppia la palabra */
  strncpy(tp->lexeme, lexeme, MAX_LEXEME - 1);
  tp->lexeme[MAX_LEXEME - 1] = '\0';
  tp->linea  = linea;
  tp->next   = idSymTbl;
  idSymTbl   = tp;
  return tp;
}

/* insertar numero */
int insert_num(char *lexeme, int tipo, int linea) {
  /* copia el texto dentro de la tabla, e indica la posicion de este*/
  strncpy(tabla_nums[count_nums].lexeme, lexeme, MAX_LEXEME - 1);
  tabla_nums[count_nums].token_type = tipo;
  tabla_nums[count_nums].linea = linea;
  return count_nums++;
}

/* insertar string */
int insert_string(char *lexeme, int linea) {
  strncpy(tabla_strings[count_strings].lexeme, lexeme, MAX_LEXEME - 1);
  tabla_strings[count_strings].linea = linea;
  return count_strings++;
}

/* agregar token */
void add_token(int token_id, int table_index, int linea, char *lexeme) {
  token_list[count_tokens].token_id    = token_id;
  token_list[count_tokens].table_index = table_index;
  token_list[count_tokens].linea       = linea;
  strncpy(token_list[count_tokens].lexeme, lexeme, MAX_LEXEME - 1);
  count_tokens++;
}

/* errores */
void print_error(char *msg, int linea, char *lexeme) {
    fprintf(stderr, "[LEXICAL ERROR] Line %d: %s -> '%s'\n",
            linea, msg, lexeme);
    error_count++;
}

/* convertir a tokens correctos */
char *token_name(int id) {
    switch(id) {
        case TK_INT: return "KW_INT";
        case TK_FLOAT: return "KW_FLOAT";
        case TK_STRING: return "KW_STRING";
        case TK_RETURN: return "KW_RETURN";
        case TK_IF: return "KW_IF";
        case TK_ELSE: return "KW_ELSE";
        case TK_WHILE: return "KW_WHILE";
        case TK_READ: return "KW_READ";
        case TK_WRITE: return "KW_WRITE";
        case TK_VOID: return "KW_VOID";
        case TK_PLUS: return "TK_PLUS";
        case TK_MINUS: return "TK_MINUS";
        case TK_MULT: return "TK_MULT";
        case TK_DIVISION: return "TK_DIVISION";
        case TK_LESSTHAN: return "TK_LT";
        case TK_LESSEQ: return "TK_LESSEQ";
        case TK_MORETHAN: return "TK_MORETHAN";
        case TK_MOREEQ: return "TK_MOREEQ";
        case TK_EQUAL: return "TK_EQUAL";
        case TK_DIF: return "TK_DIF";
        case TK_ASSIGN: return "TK_ASSIGN";
        case TK_SEMICOLON: return "TK_SEMICOLON";
        case TK_COMMA: return "TK_COMMA";
        case TK_OPAREN: return "TK_OPAREN";
        case TK_CPAREN: return "TK_CPAREN";
        case TK_OBRACKET: return "TK_OBRACKET";
        case TK_CBRACKET: return "TK_CBRACKET";
        case TK_OCURLY: return "TK_OCURLY";
        case TK_CCURLY: return "TK_CCURLY";
        case TK_ID: return "TK_ID";
        case TK_INT_NUM: return "TK_INT_NUM";
        case TK_FLOAT_NUM: return "TK_FLOAT_NUM";
        case TK_STRING_LIT: return "TK_STRING_LIT";
        default: return "UNKNOWN";
    }
}

/* imprimir todos los tokens */
void print_token_list(void) {
    printf("\n");
    printf("=============================================================\n");
    printf("  TOKEN LIST\n");
    printf("  %-4s  %-15s  %-4s  %-5s  %s\n",
           "No.", "Token", "ID", "Line", "Lexeme");
    int i;
    for (i = 0; i < count_tokens; i++) {
        printf("  %-4d  %-15s  %-4d  %-5d  %s\n",
               i + 1,
               token_name(token_list[i].token_id),
               token_list[i].token_id,
               token_list[i].linea,
               token_list[i].lexeme);
    }
    printf("  Total tokens: %d\n", count_tokens);
    printf("=============================================================\n");
}

/* imprime todas las variables o identificadores  */
void print_table_ids(void) {
    printf("\n");
    printf("=============================================================\n");
    printf("  SYMBOL TABLE: IDENTIFIERS\n");
    printf("  %-6s  %-30s  %s\n", "Index", "Lexeme", "First Line");
    struct ID *tp = idSymTbl;
    int i = 0;
    while (tp) {
        /* formato de impresion */
        printf("  %-6d  %-30s  %d\n", i, tp->lexeme, tp->linea);
        tp = tp->next;
        i++;
    }
    printf("  Total identifiers: %d\n", i);
    printf("=============================================================\n");
}

/* imprime todos los numeros  */
void print_table_nums(void) {
    printf("\n");
    printf("=============================================================\n");
    printf("  SYMBOL TABLE: NUMBERS\n");
    printf("  %-6s  %-15s  %-12s  %s\n",
           "Index", "Lexeme", "Type", "Line");
    int i;
    for ( i = 0; i < count_nums; i++) {
        printf("  %-6d  %-15s  %-12s  %d\n",
               i,
               tabla_nums[i].lexeme,
               tabla_nums[i].token_type == TK_INT_NUM ? "INTEGER" : "FLOAT",
               tabla_nums[i].linea);
    }
    printf("  Total numbers: %d\n", count_nums);
    printf("=============================================================\n");
}

/* imprime los strings encontrados */
void print_table_strings(void) {
    printf("\n");
    printf("=============================================================\n");
    printf("  SYMBOL TABLE: STRINGS\n");
    printf("  %-6s  %-40s  %s\n", "Index", "Content", "Line");
    int i;
    for (i = 0; i < count_strings; i++) {
        printf("  %-6d  %-40s  %d\n",
               i,
               tabla_strings[i].lexeme,
               tabla_strings[i].linea);
    }
    printf("  Total strings: %d\n", count_strings);
    printf("=============================================================\n");
}

/* archivo principal */
int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <archivo.cm>\n", argv[0]);
        return 1;
    }

    FILE *fp = fopen(argv[1], "r");
    if (!fp) {
        fprintf(stderr, "ERROR: No se pudo abrir '%s'\n", argv[1]);
        return 1;
    }

    printf("=============================================================\n");
    printf("  C-- Lexical Analyzer\n");
    printf("  File: %s\n", argv[1]);

    /* apuntar lex al archivo de entrada */
    yyin = fp;

    /* correr el scanner */
    while (yylex() != 0);

    fclose(fp);

    /* imprimir resultados */
    print_token_list();
    print_table_ids();
    print_table_nums();
    print_table_strings();

    /* resumen final */
    printf("\n");
    printf("=============================================================\n");
    printf("  SCAN COMPLETE\n");
    printf("  Tokens   : %d\n", count_tokens);
    printf("  IDs      : %d\n", /* contar linked list */
           ({ int n=0; struct ID*t=idSymTbl; while(t){n++;t=t->next;} n; }));
    printf("  Numbers  : %d\n", count_nums);
    printf("  Strings  : %d\n", count_strings);
    printf("  Errors   : %d\n", error_count);

    return (error_count > 0) ? 1 : 0;
}